import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../utils/api";
import { BsBookmarkCheckFill } from "react-icons/bs"
import { AiFillDelete, AiOutlinePlus } from "react-icons/ai"
import { HiPencilSquare } from "react-icons/hi2"

interface Note {
  id: string
  title: string
  content: string
}

const Home: NextPage = () => {
  const utils = api.useContext()
  const { data } = api.note.getNotes.useQuery()
  
  const deleteNote = api.note.deleteNote.useMutation({
    onMutate: () => {
      utils.note.getNotes.cancel();
      const optimisticUpdate = utils.note.getNotes.getData();

      if (optimisticUpdate) {
        utils.note.getNotes.setData(optimisticUpdate);
      }
    },
    onSettled: () => {
      utils.note.getNotes.invalidate();
    },
  });

  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-screen min-h-screen h-full w-full bg-[radial-gradient(ellipse_at_top_left,_var(--tw-gradient-stops))] from-blue-100 via-blue-300 to-blue-500 pb-20">
        <div>
          <div className="flex gap-x-3 justify-around text-5xl font-bold p-10 text-blue-500 ">
            <div className="flex flex-row gap-x-5 bg-white px-8 py-3 rounded-3xl shadow-2xl border-b-2 border-r-2 border-black">
              <BsBookmarkCheckFill />
              <h1>Notes App</h1>
            </div>
          </div>

          <Link href="/newnote">
            <div className="px-2 mt-10 ml-20 gap-x-2 w-52 flex text-center justify-center items-center cursor-pointer bg-gray-100 text-3xl rounded-full shadow-xl border-b-2 border-r-2 border-black hover:bg-blue-400 duration-300 hover:scale-110">
              <button className="py-2"> <AiOutlinePlus ></AiOutlinePlus> </button>
              <h1>New Note</h1>
            </div>
          </Link>

          <div className="grid grid-cols-6 gap-4 mr-20 mt-10 ml-20 p-20 h-full bg-gray-100 rounded-3xl shadow-2xl border-b-2 border-r-2 border-black">
            {data?.map((note, key) => {
              return (
                  <div key={key} className="bg-[conic-gradient(at_bottom_left,_var(--tw-gradient-stops))] from-sky-400 to-blue-800 border-b-2 border-r-2 border-black rounded-3xl shadow-md w-56 h-64">
                    <h1 className="mt-4 px-4 font-semibold text-xl break-all">{note.title}</h1>
                    <div className="flex justify-end gap-x-4 mr-2">
                      <Link href={ { pathname: `/${note.id}` } }> <button className="h-4 w-4 py-2"><HiPencilSquare className="text-2xl text-black hover:text-yellow-500 hover:scale-110 duration-300"></HiPencilSquare></button> </Link>
                      <button onClick={() => deleteNote.mutate( { id: note.id } )}><AiFillDelete className="text-2xl text-black hover:text-rose-800 hover:scale-110 duration-300"></AiFillDelete> </button>
                    </div>
                  </div>
              )
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
